### ISSUE TITLE
Refactor repo

### ISSUE THREAD

**Issue by izzyStewart** [nestauk/ahl_food_reformulation#107]
**Tasks**
- [ ] Refactor code in 'steps to produce analysis'
  - [ ] Add unit tests for refactored functions
- [ ] Tidy folders including archiving un-needed code 
- [ ] Create readme's for relevant folders
- [ ] Create main readme

**Steps to produce the analysis**
1. Clustering (#108)
2. Create report outputs
   1. Creating metrics table (#109)
       - Impact
       - Feasibility
       - Inclusion
   2. Metrics table analysis (#110)
   3. Impact analysis (#111)
   4. Macro-nutrient and other visuals (#112)
