### ISSUE TITLE
Identify food categories for reformulation through clustering

### ISSUE THREAD

**Issue by izzyStewart** [nestauk/ahl_food_reformulation#4]
As part of phase 1 of the reformulation project which looks to answer:
_Identify food categories that contribute the most to overall consumption of calories and core nutrients_

To tackle we are taking a two step approach. Firstly we identify groups of households by purchasing behaviour and then find out what food categories contribute to the volume of calories and core nutrients for each household group. This will involve the following analysis:

**Stage 1**
- [x] Create a simple workflow to cluster households using k-means clustering 
- [x] Test different ways to normalise the household data and different number of k and report results. Save the clusters assigned from the optimum approach
- [x] Analyse the demographic differences between clusters 
- [x] Initial analysis of kcal purchased per cluster 

**Stage 2**
- [ ] [Create new representations to test: 1 year of household purchases, household kcal contribution to volume, absolute kcal / household size (with some weighting for children)](https://github.com/nestauk/ahl_food_reformulation/issues/20)
   - [ ] [Analysis of absolute kcal / household size](https://github.com/nestauk/ahl_food_reformulation/issues/28)
- [ ] [Integrate robust clustering and evaluate results using the silhouette score](https://github.com/nestauk/ahl_food_reformulation/issues/21)
- [ ] [Refactor 'demographic' and 'categories purchased' analysis of clusters and integrate into pipeline](https://github.com/nestauk/ahl_food_reformulation/issues/22)
- [ ] [Produce analysis of kcal density purchased per cluster](https://github.com/nestauk/ahl_food_reformulation/issues/23)

**Outputs**
- [ ] [Report](https://github.com/nestauk/ahl_food_reformulation/issues/24)
- [ ] [Outputs to be used for stakeholder event](https://github.com/nestauk/ahl_food_reformulation/issues/25)
- [ ] [Table of products to be considered for reformulation](https://github.com/nestauk/ahl_food_reformulation/issues/26)

**If needed**
- [ ] [Evaluate the clusters using consequential clustering](https://github.com/nestauk/ahl_food_reformulation/issues/7)

**Next steps**
- [ ] Update pipeline to integrate metaflow
